export const ERROR_CODES = {
  // APP
  APP_VALIDATION_FAILED: "APP_VALIDATION_FAILED",
  APP_NOT_FOUND: "APP_NOT_FOUND",
  APP_UNAUTHORIZED: "APP_UNAUTHORIZED",
  APP_FORBIDDEN: "APP_FORBIDDEN",
  APP_CONFLICT: "APP_CONFLICT",

  // DOMAIN
  DOMAIN_ORDER_NOT_CONFIRMABLE: "DOMAIN_ORDER_NOT_CONFIRMABLE",
  DOMAIN_INVALID_ORDER_STATE: "DOMAIN_INVALID_ORDER_STATE",
  DOMAIN_ITEMS_NOT_MODIFIABLE: "DOMAIN_ITEMS_NOT_MODIFIABLE",

  // INFRA
  INFRA_DB_UNAVAILABLE: "INFRA_DB_UNAVAILABLE",
  INFRA_REDIS_UNAVAILABLE: "INFRA_REDIS_UNAVAILABLE",
  INFRA_KAFKA_UNAVAILABLE: "INFRA_KAFKA_UNAVAILABLE",
  INFRA_SCHEMA_REGISTRY_TIMEOUT: "INFRA_SCHEMA_REGISTRY_TIMEOUT",

  // INTERNAL
  INTERNAL_UNEXPECTED_ERROR: "INTERNAL_UNEXPECTED_ERROR",
};
